# CUDA_VISIBLE_DEVICES=0,1 python3 biggan_am_original.py

resolution: 256
target_class: 5
model: "resnet34"  # "alexnet", "inception_v3", "mit_alexnet", "mit_resnet18", or "madrylab_resnet50 vgg19_flower resnet18_CUB200",resnet34_tinyImageNet,resnet34_cifar100.
total_class: 10
dloss_function: ""  # "", "softmax", "pixelwise", or "features".
init_method: "random"  # "mean", "top", "random", or "target".
init_num: 1
n_iters: 1
use_noise_layer: True
z_num: 20
steps_per_z: 2001
lr: 0.01
dr: 0.99
alpha: 0.1
noise_std: 0.1
seed_z: 100
l_smooth: 0 # label smoothing alpha value (if 0 -> no smoothing)
intermediate_dir: "exprs/only_smoothing0.1/cifar10_class5/intermediate"
final_dir: "exprs/only_smoothing0.1/cifar10_class5/"
