resolution: 256
dataset: "cifar10"
img_size: 32 #viT=224, CNN=32 in cifar
generation_batch_size: 50
target_class: 0
model: "resnet34"  # "alexnet", "inception_v3", "mit_alexnet", "mit_resnet18", or "madrylab_resnet50" "vgg19_flower" "resnet18_CUB200" "resnet34_tinyImageNet" "resnet34_cifar100" "vit_cifar" "cct_cifar" "vit_flower" "vit_flowers102" "cct_flowers_fromScratch" "cct_flowers_finetune" "resnet50_iitpet" "resnet_place365"
total_class: 10
img_len: 50000
dloss_function: ""  # "", "softmax", "pixelwise", or "features".
init_method: "mean"  # "mean", "top", "random", or "target".
init_num: 1
n_iters: 1
use_noise_layer: False
z_num: 20
steps_per_z: 301
lr: 0.01
dr: 0.99
alpha: 0.1
noise_std: 0.1
seed_z: 555 #300
threshold: 0.94
intermediate_dir: "ours_resnet34_cifar10/intermediate"
final_dir: "ours_resnet34_cifar10"