resolution: 256
dataset: "cifar"
img_size: 32 #viT=224, CNN=32 in cifar
generation_batch_size: 50
target_class: 0
model: "resnet34"  # "alexnet", "inception_v3", "mit_alexnet", "mit_resnet18", or "madrylab_resnet50" "vgg19_flower" "resnet18_CUB200" "resnet34_tinyImageNet" "resnet34_cifar100" "vit_cifar" "cct_vit_cifar" "vit_flower"
total_class: 10
dloss_function: ""  # "", "softmax", "pixelwise", or "features".
init_method: "random"  # "mean", "top", "random", or "target".
init_num: 1
n_iters: 1
use_noise_layer: False
z_num: 20
steps_per_z: 101
lr: 0.01
dr: 0.99
alpha: 0.1
noise_std: 0.1
seed_z: 500
intermediate_dir: "cifar10/intermediate"
final_dir: "cifar10"
